### ISSUE TITLE
Value error when cypher query returns maps

### ISSUE THREAD

**Issue by maltemoeser** [technige/py2neo#240]
Trying to return a literal map in a CypherQuery raises a ValueError in [line 176 of neo4j.py,](https://github.com/nigelsmall/py2neo/blob/master/py2neo/neo4j.py#L176) stating that the object type cannot be determined.

Here is a simplified code example: https://gist.github.com/moeser/d2cd6c7222add11211ea

The Traceback:

```
Traceback (most recent call last):
  File "py2neo_return_map.py", line 16, in <module>
    """).execute()
  File "/env/lib/python2.7/site-packages/py2neo/neo4j.py", line 1061, in execute
    return CypherResults(self._execute(**params))
  File "/env/lib/python2.7/site-packages/py2neo/neo4j.py", line 1104, in __init__
    for row in content["data"]
  File "/env/lib/python2.7/site-packages/py2neo/neo4j.py", line 178, in _hydrated
    return type(data)([_hydrated(datum) for datum in data])
  File "/env/lib/python2.7/site-packages/py2neo/neo4j.py", line 176, in _hydrated
    raise ValueError("Cannot determine object type", data)
ValueError: (u'Cannot determine object type', {u'age': 66, u'name': u'Dave'})
```

**Comment by theY4Kman** [comment]
Why not allow `raw=True` or something to be passed?
