### ISSUE TITLE
Using py2neo with multiprocessing lib.

### ISSUE THREAD

**Issue by sidewaiise** [technige/py2neo#348]
I'm trying to execute cypher code while running multiple processes, however whenever the number of processes goes over 1, I get this error:

```
         Traceback (most recent call last):
         File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 634, in read
         File "filename.multi2.py", line 190, in myFunction
            data = self._response.read()
         File "/usr/lib/python2.7/httplib.py", line 543, in read
            tx.execute()
         File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher.py", line 233, in execute
            return self._post(self._execute or self._begin)
         File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher.py", line 208, in _post
            j = rs.json
         File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 562, in json
           return self._read_chunked(amt)
           raise TypeError("Content is not JSON")
        TypeError: Content is not JSON
        File "/usr/lib/python2.7/httplib.py", line 597, in _read_chunked
        ()
           raise IncompleteRead(''.join(value))
         IncompleteRead: IncompleteRead(198 bytes read)
       ()

           pool.map(myFunction, list)
        File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
           return self.map_async(func, iterable, chunksize).get()
        File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
           raise self._value
        TypeError: Content is not JSON
```

Do you know why this might happen? As I mentioned - it only occurs when my process count goes over 1.. ie. ive tried 2, 4, 8 and 16 - all create the same error.

**Comment by khafan246** [comment]
@nigelsmall What is the current state of py2neo regarding multiprocessing.
as i mentioned in #474, i struggled with many scenarios to harness multiprocessing power with no lock

**Comment by nigelsmall** [comment]
The current state is that it isn't supported.
