### ISSUE TITLE
Cypher problems in 2.0

### ISSUE THREAD

**Issue by porterjamesj** [technige/py2neo#361]
When trying to execute a simple cypher query, I get a traceback with a connection refused error:

```
>>> res = graph.cypher.execute('MATCH (n:file) RETURN n LIMIT 2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/cypher/core.py", line 110, in execute
    results = tx.commit()
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/cypher/core.py", line 294, in commit
    return self.post(self.__commit or self.__begin_commit)
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/cypher/core.py", line 255, in post
    for r in result["data"]]))
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/core.py", line 749, in hydrate
    return type(data)(map(self.hydrate, data))
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/core.py", line 718, in hydrate
    return Node.hydrate(data)
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/core.py", line 1316, in hydrate
    inst.bind(self, data)
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/core.py", line 1431, in bind
    if self.graph.supports_node_labels:
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/core.py", line 373, in graph
    return self.service_root.graph
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/core.py", line 452, in graph
    self.__graph = Graph(self.resource.metadata["data"])
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/core.py", line 198, in metadata
    self.get()
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/core.py", line 234, in get
    response = self.__base.get(headers=headers, redirect_limit=redirect_limit, **kwargs)
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 959, in get
    return self.__get_or_head("GET", if_modified_since, headers, redirect_limit, **kwargs)
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 936, in __get_or_head
    return rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 433, in submit
    http, rs = submit(self.method, uri, self.body, self.headers)
  File "/home/ubuntu/.virtualenvs/checker/local/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 362, in submit
    raise SocketError(code, description, host_port=uri.host_port)
py2neo.packages.httpstream.http.SocketError: Connection refused
```

This seems odd to me because I can definitely connect to the database, other kinds of queries work:

```
>>> graph.order
491071
```

I notice that in that traceback it looks like it's trying to make GET requests, but as far as I can tell the neo4j cypher REST APIs only use POST. Could this have something to do with it?

**Comment by harishvc** [comment]
:+1:
