### ISSUE TITLE
httpstream.httpSocketError:Connection refused

### ISSUE THREAD

**Issue by huxiaoqian** [technige/py2neo#406]
Traceback (most recent call last):
  File "test1.py", line 9, in <module>
    graph.create(a_r_b)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 704, in create
    statement = CreateStatement(self)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/create.py", line 44, in **init**
    self.supports_node_labels = self.graph.supports_node_labels
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 1078, in supports_node_labels
    return self.neo4j_version >= (2, 0)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 956, in neo4j_version
    return version_tuple(self.resource.metadata["neo4j_version"])
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 213, in metadata
    self.get()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 258, in get
    response = self.__base.get(headers=headers, redirect_limit=redirect_limit, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 966, in get
    return self.__get_or_head("GET", if_modified_since, headers, redirect_limit, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 943, in __get_or_head
    return rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 433, in submit
    http, rs = submit(self.method, uri, self.body, self.headers)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 362, in submit
    raise SocketError(code, description, host_port=uri.host_port)
py2neo.packages.httpstream.http.SocketError: Connection refused

Now I cannot establish a connection to the server by browser.
Besides the neo4j log:
WARN org.eclipse.jetty.http.HttpParser - badMessage:400 Illegal character.......

**Comment by nigelsmall** [comment]
Sorry, you'll need to provide more information than just a stack trace for new to be able to help you.

**Comment by huxiaoqian** [comment]
I just want to test the writing speed by a large data set. At the beginning of it, everything is ok. While，after  two point five million node, it error.
that's my coding:
```
def write_graph(statuses_search):
    count, results = statuses_search.search(fields=['_id', 'user', 'retweeted_mid', 'retweeted_uid'])
    print 'count:', count
    if count==0:
        return None
    node_num = 0
    rel_num = 0
    start_time = datetime.datetime.now()
    for weibo in results():
        user = weibo['user']
        retweeted_uid = weibo['retweeted_uid']
        if retweeted_uid:
            a = Node('test1', name=user)
            b = Node('test2', name=retweeted_uid)
            a_r_b = Relationship(a, 'retweete', b)
            graph.create(a, a_r_b, b)
            node_num += 2
            rel_num += 1
        else:
            a = Node('test1', name=user)
            graph.create(a)
            node_num += 1
    print 'node_num:', node_num
    print 'rel_num:', rel_num
    return start_time
        
if __name__=='__main__':
    statuses_search = getXapianWeiboByTopic(topic_id)
    start_time = write_graph(statuses_search)
```

**Comment by nigelsmall** [comment]
If you're testing performance here, you should look at batching operations into Cypher transactions rather than executing each action individually (as will be done here with `Graph.create`). Also, you probably want to look at the `timeit` module that comes with Python.

With regards to the error that you've encountered, it looks very much like the server has crashed. The Neo4j log entry that you've highlighted may be a clue here but it would be worth looking further through the logs and trying to recreate the issue with a smaller set of data.
