### ISSUE TITLE
neoauth crashes when ran with one (or zero) argument

### ISSUE THREAD

**Issue by halflings** [technige/py2neo#437]
Running neoauth without one or zero argument gives this error (with Python 3.4.0, py2neo 2.0.7):

```
Traceback (most recent call last):
  File "/usr/local/bin/neoauth", line 9, in <module>
    load_entry_point('py2neo==2.0.7', 'console_scripts', 'neoauth')()
  File "/usr/local/lib/python3.4/dist-packages/py2neo/password.py", line 158, in main
    _help(script)
  File "/usr/local/lib/python3.4/dist-packages/py2neo/password.py", line 152, in _help
    print(HELP.format(script=os.path.basename(script)))
UnicodeEncodeError: 'ascii' codec can't encode character '\xab' in position 15: ordinal not in range(128)
```

**Comment by nigelsmall** [comment]
I'm not able to recreate this error.
