### ISSUE TITLE
OGM: Weird error when adding a relation

### ISSUE THREAD

**Issue by mjmare** [technige/py2neo#543]
I getting a weird error when trying to add a relationship in py2Neo OGM 3.1.1.

I have verified in the neo4j browser that node creation statements succeed. So the connection to the database is OK. However the error points to a connection problem. 

FWIW might be related to issue #512 

[Remark: 
Worrisome is that when stepping in the Pcharm debugger through the relevant code from line _p.acted_in.add(m)_ (Related.**get** and RelatedObjects.add) the code **has** run successfully (iow the relationship was visible in the neo4j browser!). However this is not reproducible. I hope there is no race condition or something] 

```
from py2neo import (Graph,
                    Node,
                    Relationship,
                    authenticate,
                    )

from py2neo.ogm import (GraphObject,
                        Property,
                        Related,
                        RelatedFrom,
                        RelatedTo)

from uuid import uuid4

class GraphBase(GraphObject):
    __primarykey__ = 'uuid'
    uuid = Property()

    def __init__(self):
        super().__init__()
        if not self.uuid:
            self.uuid = str(uuid4())

class Movie(GraphBase):
    __primarykey__ = 'uuid'

    title = Property()
    tag_line = Property("tagline")
    released = Property()

    actors = RelatedFrom("Person", "ACTED_IN")
    directors = RelatedFrom("Person", "DIRECTED")
    producers = RelatedFrom("Person", "PRODUCED")


class Person(GraphBase):
    __primarykey__ = 'uuid'

    name = Property()
    born = Property()

    acted_in = RelatedTo(Movie)
    directed = RelatedTo(Movie)
    produced = RelatedTo(Movie)


# g = Graph('http://neo4j:test@localhost:7474', bolt=False)
# g = Graph('bolt://neo4j:test@localhost:7687')
# g = Graph(password='test', user='neo4j', bolt=True)
g = Graph('http://neo4j:test@localhost:7476', bolt=False)
g.delete_all()


p = Person()
p.name = 'Boeba'
p.born = '2000'
g.push(p)

m=Movie()
m.title = 'Neo4j saga'
g.push(m)

p.acted_in.add(m)   # <<<<< error here
g.push(p)

# print(list(Person.select(g).where("_.name =~ 'K.*'")))
# print(list(Person.select(g)))
print(list(Person.select(g).where("_.name = 'Boeba'")))
```

```
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/packages/neo4j/v1/session.py", line 124, in session
    session = self.session_pool.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/packages/neo4j/v1/bolt.py", line 419, in connect
    s = create_connection(host_port)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/ogm_test.py", line 63, in <module>
    p.acted_in.add(m)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/ogm.py", line 168, in add
    related_objects = self._related_objects
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/ogm.py", line 158, in _related_objects
    self.__db_pull__(remote_node.graph)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/ogm.py", line 225, in __db_pull__
    for r in graph.match(*self.__match_args):
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/database/__init__.py", line 610, in match
    cursor = self.run(" ".join(clauses), parameters)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/database/__init__.py", line 731, in run
    return self.begin(autocommit=True).run(statement, parameters, **kwparameters)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/database/__init__.py", line 370, in begin
    return self.transaction_class(self, autocommit)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/database/__init__.py", line 1249, in __init__
    self.session = driver.session()
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/packages/neo4j/v1/session.py", line 126, in session
    connection = connect(self.address, self.ssl_context, **self.config)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Neo4j/py2neo3/venv3/lib/python3.5/site-packages/py2neo/packages/neo4j/v1/bolt.py", line 422, in connect
    raise ProtocolError("Unable to connect to %s on port %d - is the server running?" % host_port)
py2neo.packages.neo4j.v1.exceptions.ProtocolError: Unable to connect to localhost on port 7687 - is the server running?
```

**Comment by winni-genp** [comment]
I'm having the same issue.  Here is another version of the above code that does not work:
```python
from py2neo import Graph

from py2neo.ogm import (GraphObject,
                        Property,
                        Related,
                        RelatedFrom,
                        RelatedTo)

from py2neo.types import remote


class Movie(GraphObject):
    __primarykey__ = 'uuid'

    title = Property()
    tag_line = Property("tagline")
    released = Property()

    actors = RelatedFrom("Person", "ACTED_IN")


class Person(GraphObject):
    __primarykey__ = 'uuid'

    name = Property()
    born = Property()

    acted_in = RelatedTo(Movie)

g = Graph(
    host="localhost",
    http_port=7510,
    https_port=7511,
    bolt_port=7512
)
g.delete_all()


p = Person()
p.name = 'Boeba'
p.born = '2000'
g.push(p)

m = Movie()
m.title = 'Neo4j saga'
g.push(m)

print g.driver.address  # looks good
print remote(p.__ogm__.node).graph.driver.address  # <<<<< wrong address ?!?

p.acted_in.add(m)   # <<<<< error here
g.push(p)
```

With the following output:
```
('localhost', 7512)
(u'localhost', 7687)
Traceback (most recent call last):
  File "tmp2.py", line 51, in <module>
    p.acted_in.add(m)   # <<<<< error here
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/ogm.py", line 168, in add
    related_objects = self._related_objects
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/ogm.py", line 158, in _related_objects
    self.__db_pull__(remote_node.graph)
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/ogm.py", line 225, in __db_pull__
    for r in graph.match(*self.__match_args):
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/database/__init__.py", line 610, in match
    cursor = self.run(" ".join(clauses), parameters)
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/database/__init__.py", line 731, in run
    return self.begin(autocommit=True).run(statement, parameters, **kwparameters)
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/database/__init__.py", line 370, in begin
    return self.transaction_class(self, autocommit)
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/database/__init__.py", line 1249, in __init__
    self.session = driver.session()
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/packages/neo4j/v1/session.py", line 126, in session
    connection = connect(self.address, self.ssl_context, **self.config)
  File "/local/scratch/winni/proj/EchiDNA/mandela/miniconda/lib/python2.7/site-packages/py2neo/packages/neo4j/v1/bolt.py", line 422, in connect
    raise ProtocolError("Unable to connect to %s on port %d - is the server running?" % host_port)
py2neo.packages.neo4j.v1.exceptions.ProtocolError: Unable to connect to localhost on port 7687 - is the server running?
```
