### ISSUE TITLE
Remote entity does not preserve transaction class

### ISSUE THREAD

**Issue by john-bodley** [technige/py2neo#564]
When using the HTTP transaction the remote entity reverts to using a bolt transaction resulting in future connections being refused. Note that the issue may be in part due to the fact that I'm using the non-default HTTP port.

```python
>>> graph = py2neo.Graph(host='localhost', http_port=4095, bolt=False)
>>> graph.transaction_class
<class 'py2neo.database.HTTPTransaction'>
>>> selector = py2neo.NodeSelector(graph)
>>> node = selector.select('User').where(id='john_doe').first()
>>> py2neo.types.remote(node).graph.transaction_class
<class 'py2neo.database.BoltTransaction'>
```

**Comment by johnbodley** [comment]
Note I think this may be related but I ran into a similar issue where the settings were not correctly being transferred to the remote entity causing the database connection to be attempted over the default port, 

```
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import py2neo
>>> 
>>> graph = py2neo.Graph(
...     host='localhost',
...     bolt=True,
...     bolt_port=4096,
...     http_port=4095,
... )
/usr/local/lib/python2.7/dist-packages/py2neo/packages/neo4j/v1/session.py:528: UserWarning: Bolt over TLS is only available in Python 2.7.9+ and Python 3.3+ so communications are not secure
  warn("Bolt over TLS is only available in Python 2.7.9+ and Python 3.3+ "
>>>
>>> cursor = graph.run('MATCH ()-[r]->() RETURN r LIMIT 1')
>>> relationship = cursor.next()['r']
>>> 
>>> relationship.end_node()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 857, in __repr__
    writer.write_node(self)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/cypher.py", line 139, in write_node
    for label in sorted(node.labels()):
  File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 902, in labels
    self.__ensure_labels()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 897, in __ensure_labels
    remote_self.graph.pull(self)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 685, in pull
    subgraph.__db_pull__(self)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/types.py", line 452, in __db_pull__
    tx = graph.begin()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 370, in begin
    return self.transaction_class(self, autocommit)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 1249, in __init__
    self.session = driver.session()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/neo4j/v1/session.py", line 126, in session
    connection = connect(self.address, self.ssl_context, **self.config)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/neo4j/v1/bolt.py", line 422, in connect
    raise ProtocolError("Unable to connect to %s on port %d - is the server running?" % host_port)
py2neo.packages.neo4j.v1.exceptions.ProtocolError: Unable to connect to localhost on port 7687 - is the server running?
```

In this case the graph object associated with the remote relationship no longer has the `bolt` and `bolt_port` fields, 

```
>>> graph.__dict__
{'__remote__': Resource(u'http://localhost:4095/db/data/'), 'driver': <py2neo.packages.neo4j.v1.session.Driver object at 0x7f5b08d60dd0>, 'transaction_uri': u'http://localhost:4095/db/data/transaction', 'transaction_class': <class 'py2neo.database.BoltTransaction'>, 'node_selector': <py2neo.database.selection.NodeSelector object at 0x7f5b08d60b90>, 'address': <ServerAddress settings={'host': 'localhost', 'http_port': 4095, 'bolt_port': 4096, 'bolt': True}>}
```
```
>>> relationship.__remote__.graph.__dict__
{'__remote__': Resource(u'http://localhost:4095/db/data/'), 'driver': <py2neo.packages.neo4j.v1.session.Driver object at 0x7f5b0cec6190>, 'transaction_uri': u'http://localhost:4095/db/data/transaction', 'transaction_class': <class 'py2neo.database.BoltTransaction'>, 'node_selector': <py2neo.database.selection.NodeSelector object at 0x7f5b08d75450>, 'address': <ServerAddress settings={'host': u'localhost', 'http_port': 4095}>}
```

**Comment by johnbodley** [comment]
Similarly even if you explicitly disable Bolt, the graph transaction class is correctly defined as `HTTPTransaction`

```python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import py2neo
>>>
>>> graph = py2neo.Graph(host='localhost', bolt=False, bolt_port=4096, http_port=4095)
>>> graph.__dict__
{'transaction_uri': u'http://localhost:4095/db/data/transaction', 'transaction_class': <class 'py2neo.database.HTTPTransaction'>, '__remote__': Resource(u'http://localhost:4095/db/data/'), 'node_selector': <py2neo.database.selection.NodeSelector object at 0x7f141b109d90>, 'address': <ServerAddress settings={'host': 'localhost', 'http_port': 4095, 'bolt_port': 4096, 'bolt': False}>}
```

however the remote transaction class is a `BoltTransaction` instance, I believe in part because the remote address doesn't have the bolt parameter, and thus reverts to using Bolt for all Neo4j versions > 3, https://github.com/technige/py2neo/blob/v3/py2neo/database/__init__.py#L327

```python
>>> cursor = graph.run('MATCH ()-[r]->() RETURN r LIMIT 1')
>>> relationship = cursor.next()['r']
>>> relationship.__remote__.graph.__dict__
{'__remote__': Resource(u'http://localhost:4095/db/data/'), 'driver': <py2neo.packages.neo4j.v1.session.Driver object at 0x7f141b0b75d0>, 'transaction_uri': u'http://localhost:4095/db/data/transaction', 'transaction_class': <class 'py2neo.database.BoltTransaction'>, 'node_selector': <py2neo.database.selection.NodeSelector object at 0x7f141b0bf710>, 'address': <ServerAddress settings={'host': u'localhost', 'http_port': 4095}>}
```

Additionally like before since there's no Bolt port defined it reverts to the default port of 7687.

**Comment by johnbodley** [comment]
Note here's my current workaround to ensure that the `py2neo.Graph` instance cache is used and an invalid instance with either the wrong transaction class or Bolt port isn't used. This requires that the `ServerAddress` object only includes the `bolt_port` and `http_port` parameters to ensure a cache hit. 

For the Bolt protocol, one needs to exclude the `bolt` parameter, i.e., 

```python
graph = py2neo.Graph(host='localhost', bolt_port=4096, http_port=4095)
```

For the HTTP protocol, one needs to explicitly set the transaction class, 

```python
graph = py2neo.Graph(host='localhost', bolt_port=4096, http_port=4095)
graph.transaction_class = py2neo.database.HTTPTransaction
```
