### ISSUE TITLE
Exceptions when using cycli with no authentication required

### ISSUE THREAD

**Issue by drfraser** [technige/py2neo#621]
Hi,

Perhaps this is an issue with Neo4j; I have only just started using it, cycli and py2neo. I have a server with an empty database (Neo4j version 3.1.1) and authorization has been disabled with dbms.security.auth_enabled=false. That is the only auth setting I see that might be relevant.

I can connect w/ no issue using the browser interface, but using cycli (v0.7.6, py2neo: 3.1.2) results in:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py2neo/database/__init__.py", line 318, in __new__
    inst = cls.__instances[key]
KeyError: (<class 'py2neo.database.Graph'>, <ServerAddress settings={'host': 'localhost', 'http_port': 7474, 'bolt': None, 'secure': False}>, 'data')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py2neo/database/http.py", line 154, in get
    response = self.__base.get(headers=headers, redirect_limit=redirect_limit, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 966, in get
    return self.__get_or_head("GET", if_modified_since, headers, redirect_limit, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 943, in __get_or_head
    return rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 452, in submit
    return Response.wrap(http, uri, self, rs, **response_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 489, in wrap
    raise inst
py2neo.packages.httpstream.http.ClientError: 401 Unauthorized

When I use 'cycli -u neo4j' and enter a password, then things are fine, I get a prompt etc. If I have something misconfigured, please let me know.

**Comment by wgwz** [comment]
Hi, there. Have you resolved this issue? Did you raise the issue in cycli as well? It looks like it could be something on that side. Neat looking tool by the way

**Comment by drfraser** [comment]
No, I did not raise it in cycli, I ended up not using it or py2neo - went with cypher-shell as it was sufficient. So you want me to do that?  And what tool, Revuze?  Thanks - haven't done anything with it yet due to school / would anyone care...

**Comment by wgwz** [comment]
I think cycli is neat looking! But yeah if you want a solution I'd raise it there. But I'd also check the issue again with the latest version of cycli, to see if it has been fixed. And in the meantime you can close this issue here. If something comes of if, hopefully someone on the cycli side will raise another issue here.

**Comment by wgwz** [comment]
@drfraser just so you know, I'm not technige as you said in the cycli issue. Just a fellow traveler trying to help out the py2neo project.
