### ISSUE TITLE
“Operation timed out”…but data still uploads

### ISSUE THREAD

**Issue by owenbrown** [technige/py2neo#625]
Hi, I also posted this in StackOverflow.

0
down vote
favorite
I'm running Neo4j 3.1.3 on Python 2.7 on an AWS EC2 instance.

I'm trying to run a simple hello-world update.
```
from py2neo import Graph, Node
from py2neo.ogm import Property, GraphObject
from config import config

### I tried the line below already. Didn't help.
# from py2neo.packages.httpstream import http
# http.socket_timeout = 1000 * 60 * 5


g = Graph(
    bolt_port=7687,
    https_port=7473,
    bolt=True,
    secure=False,
    host='50.40.230.27',
    user='neo4j',
    password='falcon')


class MyNodeClass(GraphObject):
    __primarykey__ = "name"
    name = Property()


if __name__ == '__main__':
        tx = g.begin(autocommit=False)
        new_node = Node("MyNodeClass", name='empire')
        new_node['hero'] = 'leah'
        new_node['rouge'] = 'han'
        new_node['wookie'] = 'chewy'
        tx.create(new_node)
        tx.commit()
        print('finished committing')
```
I can run this locally and it works fine. When I run it on my remote server - on an EC2 instance - I consistently get this error -
```
Traceback (most recent call last):
  File "/Users/myusername/myproject/graphs/graph_py2neo_example.py", line 33, in <module>
    tx.commit()
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 1059, in commit
    self._post(commit=True)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 1291, in _post
    self.finish()
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 1296, in finish
    self._sync()
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 1286, in _sync
    connection.fetch()
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/packages/neo4j/v1/bolt.py", line 344, in fetch
    handler(*fields)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 944, in on_record
    v = self.rehydrate(bolt_hydrate(value), inst=cached)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 970, in rehydrate
    }, inst)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/types.py", line 838, in hydrate
    inst.__remote__ = RemoteEntity(self, data)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/types.py", line 692, in __init__
    self.ref = self.uri.string[len(remote(self.graph).uri.string):]
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/http.py", line 104, in graph
    return self.__dbms.graph
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 151, in graph
    return self["data"]
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 137, in __getitem__
    return Graph(database=database, **dict(self.address))
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/__init__.py", line 327, in __new__
    use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/database/http.py", line 154, in get
    response = self.__base.get(headers=headers, redirect_limit=redirect_limit, **kwargs)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 966, in get
    return self.__get_or_head("GET", if_modified_since, headers, redirect_limit, **kwargs)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 943, in __get_or_head
    return rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 433, in submit
    http, rs = submit(self.method, uri, self.body, self.headers)
  File "/Users/myusername/myproject/virtual_environments/myproject_env/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 362, in submit
    raise SocketError(code, description, host_port=uri.host_port)
py2neo.packages.httpstream.http.SocketError: Operation timed out
```
I thought changing the http.socket_timeout would help but it doesn't help.

What is strange is that the node is added to the database. So, my password and other settings must be correct. But, the program errors out, So I'm not able to execute a program that adds multiple nodes, etc.

Please help me with this.

**Comment by owenbrown** [comment]
I was able to resolve this by setting "secure" to True. The SocketError could be more descriptive...could have saved me time by telling me to use Secure.
