### ISSUE TITLE
neokit (in v. 4.0.0b2) tries to open versions.txt that is not there

### ISSUE THREAD

**Issue by pvanheus** [technige/py2neo#632]
When I run `neokit` I get:

````
$ neokit
Traceback (most recent call last):
  File "/home/pvh/.virtualenvs/test/bin/neokit", line 7, in <module>
    from neokit import main
  File "/home/pvh/.virtualenvs/test/local/lib/python2.7/site-packages/neokit.py", line 125, in <module>
    versions = open(path_join(ROOT_DIR, "versions.txt")).read().split()
IOError: [Errno 2] No such file or directory: '/home/pvh/.virtualenvs/test/local/lib/python2.7/site-packages/versions.txt'
````
The file in question is indeed not there. It exists in the root of the Github repository but not in the python package.

**Comment by wgwz** [comment]
It could be that versions.txt needs to be added to the MANIFEST.in
