### ISSUE TITLE
Failing to install the latest beta

### ISSUE THREAD

**Issue by Lawouach** [technige/py2neo#635]
Trying install it, I get the following:

```
$ pip install --upgrade git+https://github.com/technige/py2neo.git#egg=py2neo
Collecting py2neo from git+https://github.com/technige/py2neo.git#egg=py2neo
  Cloning https://github.com/technige/py2neo.git to /tmp/pip-build-c470cs8y/py2neo
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c470cs8y/py2neo/setup.py", line 24, in <module>
        from py2neo.meta import __author__, __email__, __license__, __package__, __version__
      File "/tmp/pip-build-c470cs8y/py2neo/py2neo/__init__.py", line 19, in <module>
        from py2neo.ext import *
      File "/tmp/pip-build-c470cs8y/py2neo/py2neo/ext/__init__.py", line 19, in <module>
        from py2neo.graph import GraphError
      File "/tmp/pip-build-c470cs8y/py2neo/py2neo/graph.py", line 30, in <module>
        from py2neo.types import cast_node, Subgraph, Node, Relationship
      File "/tmp/pip-build-c470cs8y/py2neo/py2neo/types.py", line 22, in <module>
        from cypy.data import size
    ImportError: cannot import name 'size'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c470cs8y/py2neo/
```

**Comment by AlJohri** [comment]
I get something similar except it can't find `cypy.encoding`
