### ISSUE TITLE
Invalid input '<': expected <init>

### ISSUE THREAD

**Issue by Wenzel** [technige/py2neo#636]
Hi !

I'm trying to use your driver to upload a filesystem to a neo4j db.

As i don't want to update the remote graph at each inode i found while i'm walking through the fileystem, i created a transaction.

However, i have the following error when i try to commit the transaction:

~~~
INFO:root:[100.0 %] /vmlinuz
INFO:root:Committing graph transaction...
Traceback (most recent call last):
  File "./collect_vm.py", line 132, in <module>
    main(docopt(__doc__))
  File "./collect_vm.py", line 128, in main
    vm.capture_filesystem()
  File "./collect_vm.py", line 84, in capture_filesystem
    self.tx.commit()
  File "/home/wenzel/ownCloud/Projets/oswatcher/venv/lib/python3.5/site-packages/py2neo/database/__init__.py", line 1059, in commit
    self._post(commit=True)
  File "/home/wenzel/ownCloud/Projets/oswatcher/venv/lib/python3.5/site-packages/py2neo/database/__init__.py", line 1291, in _post
    self.finish()
  File "/home/wenzel/ownCloud/Projets/oswatcher/venv/lib/python3.5/site-packages/py2neo/database/__init__.py", line 1296, in finish
    self._sync()
  File "/home/wenzel/ownCloud/Projets/oswatcher/venv/lib/python3.5/site-packages/py2neo/database/__init__.py", line 1286, in _sync
    connection.fetch()
  File "/home/wenzel/ownCloud/Projets/oswatcher/venv/lib/python3.5/site-packages/py2neo/packages/neo4j/v1/bolt.py", line 344, in fetch
    handler(*fields)
  File "/home/wenzel/ownCloud/Projets/oswatcher/venv/lib/python3.5/site-packages/py2neo/database/__init__.py", line 961, in on_failure
    raise GraphError.hydrate(metadata)
py2neo.database.status.CypherSyntaxError: Invalid input '<': expected <init> (line 1, column 1 (offset: 0))
"<Inode __id__=None>"
 ^
./collect_vm.py ubuntu  60,49s user 15,67s system 64% cpu 1:58,68 total
~~~

The only operation i'm doing is adding all the Inodes object into the transaction: https://github.com/Wenzel/oswatcher/blob/neo4j/collect_vm.py#L109

And at the end, committing it: https://github.com/Wenzel/oswatcher/blob/neo4j/collect_vm.py#L84

Did i forgot to specify a property in my Inode class maybe ?
https://github.com/Wenzel/oswatcher/blob/neo4j/model.py
Could you explain this error ?

Many thanks !

**Comment by technige** [comment]
You are running invalid Cypher. This is not a py2neo problem.
