### ISSUE TITLE
pyneo can't not perform Graph.run() when server's bolt_port is customized to other ports.

### ISSUE THREAD

**Issue by lmwsky** [technige/py2neo#655]
First the server's bolt_port default is 7687, But it is customized to other ports--7688.
And the neo4j instance is running correctly. When I use py2neo for some simple query operations which just need to go through the http port and everything works. When I use a complex query, it needs to go through the bolt port and the problem arises.

```
Traceback (most recent call last):
  File "E:\project\laboratory\SKnowledgeGraph\test\test_graphClient.py", line 132, in test_get_shortest_path
    record_list = self.graphClient.get_shortest_path(444, 8000)
  File "E:\project\laboratory\SKnowledgeGraph\graph\graph_util\question_answer_system\graph\graph_client.py", line 547, in get_shortest_path
    result = self.graph.run(query)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 731, in run
    return self.begin(autocommit=True).run(statement, parameters, **kwparameters)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 1208, in run
    self.commit()
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 1059, in commit
    self._post(commit=True)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 1233, in _post
    source.load(raw_result)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 887, in load
    values.append(hydrate(value, inst=cached))
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 538, in _hydrate
    return Path.hydrate(data)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\types.py", line 1153, in hydrate
    inst = Path(*round_robin(nodes, relationships))
  File "E:\work\Anaconda2\lib\site-packages\py2neo\types.py", line 1178, in __init__
    Walkable.__init__(self, walk(*entities))
  File "E:\work\Anaconda2\lib\site-packages\py2neo\types.py", line 536, in __init__
    Subgraph.__init__(self, self.__sequence[0::2], self.__sequence[1::2])
  File "E:\work\Anaconda2\lib\site-packages\py2neo\types.py", line 219, in __init__
    self.__relationships = frozenset(relationships or [])
  File "E:\work\Anaconda2\lib\site-packages\py2neo\types.py", line 1080, in __hash__
    return hash(self.nodes()) ^ hash(self.type())
  File "E:\work\Anaconda2\lib\site-packages\py2neo\types.py", line 1108, in type
    remote_self.graph.pull(self)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 685, in pull
    subgraph.__db_pull__(self)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\types.py", line 448, in __db_pull__
    tx = graph.begin()
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 370, in begin
    return self.transaction_class(self, autocommit)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\database\__init__.py", line 1249, in __init__
    self.session = driver.session()
  File "E:\work\Anaconda2\lib\site-packages\py2neo\packages\neo4j\v1\session.py", line 126, in session
    connection = connect(self.address, self.ssl_context, **self.config)
  File "E:\work\Anaconda2\lib\site-packages\py2neo\packages\neo4j\v1\bolt.py", line 419, in connect
    s = create_connection(host_port)
  File "E:\work\Anaconda2\lib\socket.py", line 575, in create_connection
    raise err
error: [Errno 10061] 
-------------------- >> begin captured logging << --------------------
httpstream: INFO: > POST http://10.141.221.75:7475/db/data/transaction/commit [214]
httpstream: DEBUG: > Host: 10.141.221.75:7475
httpstream: DEBUG: > Content-Type: application/json
httpstream: DEBUG: > X-Stream: true
httpstream: DEBUG: > Authorization: Basic bmVvNGo6MTIzNDU2
httpstream: DEBUG: > User-Agent: py2neo/3.1.2 HTTPStream/1.5.0 Python/2.7.13-final-0 (win32)
httpstream: INFO: < 200 OK [1174]
httpstream: DEBUG: < date: Thu, 22 Mar 2018 08:29:16 GMT
httpstream: DEBUG: < access-control-allow-origin: *
httpstream: DEBUG: < content-type: application/json
httpstream: DEBUG: < content-length: 1174
httpstream: DEBUG: < server: Jetty(9.2.22.v20170606)
httpstream: INFO: > GET http://10.141.221.75:7475/db/data/
httpstream: DEBUG: > Host: 10.141.221.75:7475
httpstream: DEBUG: > X-Stream: true
httpstream: DEBUG: > Authorization: Basic bmVvNGo6MTIzNDU2
httpstream: DEBUG: > User-Agent: py2neo/3.1.2 HTTPStream/1.5.0 Python/2.7.13-final-0 (win32)
httpstream: INFO: < 200 OK [843]
httpstream: DEBUG: < date: Thu, 22 Mar 2018 08:29:16 GMT
httpstream: DEBUG: < access-control-allow-origin: *
httpstream: DEBUG: < content-type: application/json; charset=UTF-8
httpstream: DEBUG: < content-length: 843
httpstream: DEBUG: < server: Jetty(9.2.22.v20170606)
neo4j.bolt: INFO: ~~ [CONNECT] (u'10.141.221.75', 7687)
--------------------- >> end captured logging << ---------------------
```
py2neo will connect to old default 7687 port, not the 7688 port.
I check the code.
```
    def __new__(cls, *uris, **settings):
        database = settings.pop("database", "data")
        address = register_server(*uris, **settings)
        key = (cls, address, database)
        try:
            inst = cls.__instances[key]
        except KeyError:
            inst = super(Graph, cls).__new__(cls)
            inst.address = address
            inst.__remote__ = Resource(address.http_uri("/db/%s/" % database))
            inst.transaction_uri = Resource(address.http_uri("/db/%s/transaction" % database)).uri.string
            inst.transaction_class = HTTPTransaction
            use_bolt = address.bolt
            if use_bolt is None:
                use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)
            if use_bolt:
                auth = get_auth(address)
                inst.driver = GraphDatabase.driver(address.bolt_uri("/"),
                                                   auth=None if auth is None else auth.bolt_auth_token,
                                                   encrypted=address.secure,
                                                   user_agent="/".join(PRODUCT))
                inst.transaction_class = BoltTransaction
            inst.node_selector = NodeSelector(inst)
            cls.__instances[key] = inst
        return inst
```
in
```
            inst.__remote__ = Resource(address.http_uri("/db/%s/" % database))

```
it will only save the url that has http port info to  inst.__remote__,the bolt_port is not saved.

in the following code:
```
    def type(self):
        """ The type of this relationship.
        """
        remote_self = remote(self)
        if remote_self and self.__type is None:
            remote_self.graph.pull(self)
        return self.__type
```

it will use the remote_self = remote(self) to pull data. and it only have default bolt_port? Maybe this is the reason for following error?

Will it be possible to fix this problem?

**Comment by technige** [comment]
There were a number of similar address configuration issues in v3 which should have now been fixed in v4.

**Comment by technige** [comment]
v4 has now been released which should address this problem.
