### ISSUE TITLE
WriteBatch add_labels & set_labels got error: set(['Person', 'Movie']) is not JSON serializable

### ISSUE THREAD

**Issue by dreamerxiong** [technige/py2neo#656]
When I was trying to set labels for the node I want to create, I got the type error below:

```
>>> from py2neo.ext.batman.batch import WriteBatch
>>> from py2neo import Node
>>> from libraries.dbs.graph import MyGraph
>>> g=MyGraph()
>>> wb=WriteBatch(g)
>>> job=wb.create(Node(name="test_add_labels"))
>>> wb.set_labels(job, "Person", "Movie")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\py2neo\ext\batman\jobs.py", line 143, in __repr__
    parts.append(json.dumps(self.body, separators=",:"))
  File "C:\Python27\lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set(['Person', 'Movie']) is not JSON serializable

```

**Need probably to change the py2neo.ext.batman.job module to convert the `set(labels)` back to list type**

```
class AddNodeLabelsJob(Job):
    def __init__(self, node, *labels):
        Job.__init__(self, "POST", Target(node, "labels"), set(labels))

class PushNodeLabelsJob(Job):

    def __init__(self, node, labels):
        Job.__init__(self, "PUT", Target(node, "labels"), set(labels))

class Job(Relatable):
    def __repr__(self):
        parts = [self.method, self.target.uri_string]
        if self.body is not None:
            parts.append(json.dumps(self.body, separators=",:"))
        return " ".join(parts)```

**Comment by PerfectiisShit** [comment]
This issue is happening in version 3.1.2

**Comment by PerfectiisShit** [comment]
Another issue is that BatchRunner always sends the "POST" requests no matter what the job's method is, could also be a problem when you try to send "PUT" or "DELETE" requests

**Comment by technige** [comment]
Sorry, but I'm no longer supporting the Batch functionality as this has been legacy in Neo4j for some time and will be removed completely in 4.0. The latest version of py2neo (v4) no longer has batch capabilities for this reason.

I recommend using transactions instead and upgrading to v4.
