### ISSUE TITLE
How to completely delete nodes

### ISSUE THREAD

**Issue by wuhuanyan** [technige/py2neo#680]
```
    tx = graph.begin()
    nodes = graph.nodes
    for node in nodes:
        tx.delete(node)
    tx.commit()
```
I want to empty my NEO4J database
When I deleted nodes in the above method, there was an error:
```
Traceback (most recent call last):
  File "/Users/admin/Downloads/python_projects/other/mysql_to_neo4j/main.py", line 57, in <module>
    test_neo4j()
  File "/Users/admin/Downloads/python_projects/other/mysql_to_neo4j/main.py", line 50, in test_neo4j
    for node in nodes:
  File "/anaconda3/envs/study/lib/python3.6/site-packages/py2neo/matching.py", line 179, in __getitem__
    raise KeyError("Node %d not found" % identity)
KeyError: 'Node 0 not found'
```
So I wonder if the nodes are not completely deleted.

**Comment by technige** [comment]
This will be a very inefficient (not to mention racey) way of deleting nodes. Your best option is to use `graph.run("MATCH (a) DETACH DELETE a")` or the `graph.delete_all()` method.
