### ISSUE TITLE
failed to install through pip install py2neo command

### ISSUE THREAD

**Issue by AltheimIcarus** [technige/py2neo#687]
When entered `pip install py2neo` in cmd, below is the error i got:

Collecting py2neo
  Using cached https://files.pythonhosted.org/packages/cd/79/a77cc0ad86c021c25dac9f52a0cd33f6832c6af7fa5e58f4438d781ae9c3/py2neo-4.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\user\appdata\local\temp\pip-install-2ptk9z\py2neo\setup.py", line 25, in <module>
        from py2neo.meta import __author__, __email__, __license__, __package__, __version__
      File "c:\users\user\appdata\local\temp\pip-install-2ptk9z\py2neo\py2neo\__init__.py", line 19, in <module>
        from py2neo.data import *
      File "c:\users\user\appdata\local\temp\pip-install-2ptk9z\py2neo\py2neo\data.py", line 26, in <module>
        from py2neo.cypher import LabelSetView, cypher_repr, cypher_str
      File "c:\users\user\appdata\local\temp\pip-install-2ptk9z\py2neo\py2neo\cypher\__init__.py", line 36, in <module>
        from py2neo.internal.collections import SetView
      File "c:\users\user\appdata\local\temp\pip-install-2ptk9z\py2neo\py2neo\internal\collections.py", line 24, in <module>
        from py2neo.internal.compat import bytes_types, string_types
      File "c:\users\user\appdata\local\temp\pip-install-2ptk9z\py2neo\py2neo\internal\compat.py", line 45, in <module>
        DEVNULL = open(devnull, "rw")
    ValueError: Invalid mode ('rw')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\user\appdata\local\temp\pip-install-2ptk9z\py2neo\

using pip v18.0, windows 10 basic, python 2.7

**Comment by AltheimIcarus** [comment]
fixed by changing `DEVNULL = open(devnull, "rw")` in line 45 of `<temp_dir>\pip-install-<some_rand_char>\py2neo\py2neo\internal\compat.py` to `DEVNULL = open(devnull, "r+")`

Then run `pip install <temp_dir>\pip-install-<some_rand_char>\py2neo\` where the setup.py is located.
**Note**: 'rw' mode is not supported in some version of python. Mine is python 2.7.

**Comment by jayped007** [comment]
Was this change lost?  I am getting the same error now when installing the latest version (4.1) from pypi in a python 2.7 installation  (see issue 704).
