### ISSUE TITLE
Can't access dict keys in records returned by cursor

### ISSUE THREAD

**Issue by TomGroves** [technige/py2neo#696]
I can't access records from a cursor in the way described in the docs:
```
        cursor=self.graph.run("MATCH (file:File {sha256:{fileHash}})-[:sightedAt]->(fs:FileSighting) "
                              "RETURN fs "
                              "ORDER BY fs.datetime DESC ", fileHash=fileHash)
        while cursor.forward():
            print(cursor.current["datetime"])
```
gives
```
Traceback (most recent call last):
  File "/home/nowan/.local/lib/python3.6/site-packages/py2neo/data.py", line 149, in index
    return self.__keys.index(key)
ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nowan/Coding/GUPS/GUPSgatekeeper.py", line 66, in getFileSightings
    print(cursor.current["datetime"])
  File "/home/nowan/.local/lib/python3.6/site-packages/py2neo/data.py", line 111, in __getitem__
    index = self.index(key)
  File "/home/nowan/.local/lib/python3.6/site-packages/py2neo/data.py", line 151, in index
    raise KeyError(key)
KeyError: 'datetime'
```
whereas just printing the record itself:
`print(cursor.current)`
gives
```
<Record fs=(_26:FileSighting {datetime: '2018-09-20T11:38:33.004339', path: '/imaginary/path/filename.mkv'})>
<Record fs=(_24:FileSighting {datetime: '2018-09-20T11:38:05.204867', path: '/imaginary/path/filename.mkv'})>
<Record fs=(_23:FileSighting {datetime: '2018-09-20T11:35:31.272371', path: '/imaginary/path/filename.mkv'})>
<Record fs=(_27:FileSighting {datetime: '2018-09-20T11:33:38.343776', path: '/imaginary/path/filename.mkv'})>
<Record fs=(_22:FileSighting {datetime: '2018-09-20T11:32:50.151435', path: '/imaginary/path/filename.mkv'})>
<Record fs=(_20:FileSighting {datetime: '2018-09-20T11:20:12.745197', path: '/imaginary/path/filename.mkv'})>
<Record fs=(_17:FileSighting {datetime: '2018-09-19T22:02:22.928531', path: '/imaginary/path/filename.mkv'})>
```
showing that the records returned are as expected, and have the 'datetime' property key.

Reading the source code eventually revealed to me that even if just one node is returned in a record (as above), it's still stored in a dict, keyed by the name of the variable it was returned in, so what is required is
```
        while cursor.forward():
            print(cursor.current["fs"]["datetime"])
```
As such, I think this is a documentation issue rather than a bug, but I'm leaving it here in case it helps someone else!
Also, what's with the exception during handling of the exception? I wasn't catching that exception, so that feels like a bug...

**Comment by technige** [comment]
Your query returns one field called `fs` (a node) and that node contains a property called `datetime`. As such, the `cursor.current["fs"]["datetime"]` expression that you end up with is entirely expected and (IMHO) intuitive. As explained in the docs, a cursor allows you to navigate the records in a result and each record may contain one or more fields. Yours contains just one. This is very similar to SQL.
