### ISSUE TITLE
issue with merge and special characters

### ISSUE THREAD

**Issue by stuartlaurie** [technige/py2neo#701]
Using py2neo v4

There seems to be an issue when using merge, if for example a node with the name:

`accountID/paymentInstrument/-piID`

I can successfully create that node using g.create but when i try to merge using the same id e.g.

```
a = Node("API", name = "accountID/paymentInstrument/-piID")
g.merge(a,"API","name")
```

I get the following error:

```
(:API {name: 'accountID/paymentInstrument/-piID'})
Traceback (most recent call last):
  File "./py2neo_merge.py", line 30, in <module>
    g.merge(a,"API","name")
  File "/anaconda2/lib/python2.7/site-packages/py2neo/database.py", line 427, in merge
    tx.merge(subgraph, label, *property_keys)
  File "/anaconda2/lib/python2.7/site-packages/py2neo/database.py", line 1002, in merge
    merge(self, primary_label, primary_key)
  File "/anaconda2/lib/python2.7/site-packages/py2neo/data.py", line 620, in __db_merge__
    merge_subgraph(tx, self, primary_label, primary_key)
  File "/anaconda2/lib/python2.7/site-packages/py2neo/internal/operations.py", line 167, in merge_subgraph
    node = nodes[i]
IndexError: list index out of range
```

**Comment by 786country** [comment]
I have encountered a similar issue but my property does not have special characters. 

 File "profile_py2neo.py", line 98, in PY2NEO_FUNC
    tx.merge(b, primary_label='Named_Entity_New', primary_key='Value')
  File "/usr/local/lib/python3.5/dist-packages/py2neo/database.py", line 991, in merge
    merge(self, primary_label, primary_key)
  File "/usr/local/lib/python3.5/dist-packages/py2neo/data.py", line 624, in __db_merge__
    merge_subgraph(tx, self, primary_label, primary_key)
  File "/usr/local/lib/python3.5/dist-packages/py2neo/internal/operations.py", line 168, in merge_subgraph
    node = nodes[i]
IndexError: list index out of range

**Comment by technige** [comment]
Likely fixed by https://github.com/technige/py2neo/commit/13856e262afafc4bd8da567a15b0de5342c0a66e

**Comment by technige** [comment]
Closing as this should be fixed in the latest release. Please reopen if not.

**Comment by benjaminlaird** [comment]
This appears to still be a bug in certain cases. I have no special characters in my Label/Property names but this seems to fail as I have two separate nodes in the database already that match. 

```
    for (pl, pk, labels), nodes in _node_merge_dict(p_label, p_key, (n for n in subgraph.nodes if n.graph is None)).items():
        if pl is None or pk is None:
            raise ValueError("Primary label and primary key are required for MERGE operation")
        print(nodes) #ADDED
        identities = _merge_nodes(tx, pl, pk, labels, list(map(lambda n: [n.get(pk), dict(n)], nodes)))
        identities = list(identities) #ADDED
        print(identities) # ADDED
        for i, identity in enumerate(identities):
            node = nodes[i]
```
There are 2 node IDs (identities list) returned that match the existing node being merged. However, there is only 1 node, so `nodes[1]` does not exist.
```
[(:Company {uuid: XXX})] 
[2549818, 3254358] 
Traceback (most recent call last):
  File "crunchbase/crunchbase_bulk_loader.py", line 79, in <module>
    CBInvestment(path).load()
  File "crunchbase/crunchbase_bulk_loader.py", line 62, in load
    tx.merge(subgraph)
  File "C:\PF\Anaconda3\lib\site-packages\py2neo\database.py", line 975, in merge
    merge(self, primary_label, primary_key)
  File "C:\PF\Anaconda3\lib\site-packages\py2neo\data.py", line 618, in __db_merge__
    merge_subgraph(tx, self, primary_label, primary_key)
  File "C:\PF\Anaconda3\lib\site-packages\py2neo\internal\operations.py", line 172, in merge_subgraph
    node = nodes[i]
IndexError: list index out of range
```
