### ISSUE TITLE
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason 10061)

### ISSUE THREAD

**Issue by scofield7419** [technige/py2neo#706]
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\py2neo\database.py", line 88, in __new__
    inst = cls._instances[key]
**KeyError: '4ddf1890350c0edfa6ddd479a0008624'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/visualizing/test.py", line 3, in <module>
    test_graph = Graph()
  File "D:\Python35\lib\site-packages\py2neo\database.py", line 305, in __new__
    database = Database(uri, **settings)
  File "D:\Python35\lib\site-packages\py2neo\database.py", line 97, in __new__
    user_agent=connection_data["user_agent"])
  File "D:\Python35\lib\site-packages\neo4j\v1\api.py", line 133, in __new__
    return subclass(uri, **config)
  File "D:\Python35\lib\site-packages\neo4j\v1\direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "D:\Python35\lib\site-packages\neo4j\v1\direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "D:\Python35\lib\site-packages\neo4j\bolt\connection.py", line 450, in acquire_direct
    connection = self.connector(address, self.connection_error_handler)
  File "D:\Python35\lib\site-packages\neo4j\v1\direct.py", line 70, in connector
    return connect(address, security_plan.ssl_context, error_handler, **config)
  File "D:\Python35\lib\site-packages\neo4j\bolt\connection.py", line 704, in connect
    raise last_error
  File "D:\Python35\lib\site-packages\neo4j\bolt\connection.py", line 694, in connect
    s = _connect(resolved_address, **config)
  File "D:\Python35\lib\site-packages\neo4j\bolt\connection.py", line 584, in _connect
    raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error.errno))
**neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason 10061)**

**_I just can't figure out why this bug comes to me, while anybody else does not._**

**Comment by scofield7419** [comment]
`from py2neo import Graph, Node, Relationship

test_graph = Graph()

test_node_1 = Node(label="Person", name="test_node_1")
test_node_2 = Node(label="Person", name="test_node_2")
test_graph.create(test_node_1)
test_graph.create(test_node_2)

node_1_call_node_2 = Relationship(test_node_1, 'CALL', test_node_2)
node_1_call_node_2['count'] = 1
node_2_call_node_1 = Relationship(test_node_2, 'CALL', test_node_1)
node_2_call_node_1['count'] = 2
test_graph.create(node_1_call_node_2)
test_graph.create(node_2_call_node_1)`

Everything in my code is normal...

**Comment by technige** [comment]
This is simply failing to establish a TCP connection and it most likely a problem with your environment. Make sure your server is listening on the IP address and port that you think it is. I can't do much else to help here.
