### ISSUE TITLE
py2neo.database.Graph.create/merge fails with GraphObject

### ISSUE THREAD

**Issue by mudsill** [technige/py2neo#723]
With `py2neo 4.1.3`:

I'm using `multiprocessing` to distribute node creation tasks. My OGM model is defined as:

```
class Country(GraphObject):
    __primarykey__ = 'name'

    countryID = Property()
    name = Property()
    abbrev = Property()

    has_country = RelatedFrom(State)
```

When I instantiate this model, set the `name` property (and `__primaryvalue__`), and try to add to the graph using `py2neo.database.Graph.merge`, I get the following error:

```
Traceback (most recent call last):
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/lion/Projects/graph-generator/ggen/operations.py", line 10, in expand
    to_node = db.merge_node(generators.get(to_node_gen), to_node_props)
  File "/Users/lion/Projects/graph-generator/ggen/drivers.py", line 75, in merge_node
    self.graph.merge(model)
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/database.py", line 434, in merge
    tx.merge(subgraph, label, *property_keys)
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/database.py", line 1000, in merge
    merge(self, primary_label, primary_key)
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/ogm.py", line 411, in __db_merge__
    tx.merge(node, primary_label, primary_key)
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/database.py", line 1000, in merge
    merge(self, primary_label, primary_key)
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/data.py", line 624, in __db_merge__
    merge_subgraph(tx, self, primary_label, primary_key)
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/internal/operations.py", line 167, in merge_subgraph
    for i, identity in enumerate(identities):
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/internal/operations.py", line 105, in _merge_nodes
    for record in tx.run(cypher, x=data):
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/database.py", line 863, in run
    r = Result(self.graph, entities, result)
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/py2neo/database.py", line 626, in __init__
    self.result._hydrant = PackStreamHydrator(graph, result.keys(), entities)
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/neo4j/v1/api.py", line 720, in keys
    self._session.fetch()
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/neo4j/v1/api.py", line 347, in fetch
    detail_count, _ = self._connection.fetch()
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 287, in fetch
    return self._fetch()
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 327, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/lion/Projects/graph-generator/venv/lib/python3.7/site-packages/neo4j/v1/result.py", line 70, in on_failure
    raise CypherError.hydrate(**metadata)
neo4j.exceptions.ClientError: Cannot merge node using null property value for name
```

`name` isn't null for any of the nodes being created, and neither is `__primaryvalue__`. Any idea of what might be happening here? Thanks.

**Comment by anabase** [comment]
I should add that this seems to be happening even when I try to manually add `GraphObject` objects to my DB using `py2neo.database.Graph.merge`.

**Comment by technige** [comment]
Closing due to inactivity.
