### ISSUE TITLE
another issue with merge and special characters

### ISSUE THREAD

**Issue by ss433s** [technige/py2neo#737]
the code is

`graph.merge(label,'LABEL','value')`

the error is 

`Traceback (most recent call last):
  File "load_data.py", line 16, in <module>
    graph.merge(label,'LABEL','value')
  File "/data/apps/anaconda3/envs/python36/lib/python3.6/site-packages/py2neo/database.py", line 434, in merge
    tx.merge(subgraph, label, *property_keys)
  File "/data/apps/anaconda3/envs/python36/lib/python3.6/site-packages/py2neo/database.py", line 1000, in merge
    merge(self, primary_label, primary_key)
  File "/data/apps/anaconda3/envs/python36/lib/python3.6/site-packages/py2neo/data.py", line 624, in __db_merge__
    merge_subgraph(tx, self, primary_label, primary_key)
  File "/data/apps/anaconda3/envs/python36/lib/python3.6/site-packages/py2neo/internal/operations.py", line 168, in merge_subgraph
    node = nodes[i]
IndexError: list index out of range`

almost exactly as https://github.com/technige/py2neo/issues/701

change the primary label to another word would work.

sorry I just used such a 'label'

anyway, it will be better if this could be fixed....

**Comment by technige** [comment]
Have you tried with the latest release? A bug fix went out for this kind of problem a while back.

**Comment by technige** [comment]
Closing issue as should have been addressed in 4.2. Please reopen if still broken.
