### ISSUE TITLE
Unable to connect - Keyerror

### ISSUE THREAD

**Issue by GeoWonk** [technige/py2neo#739]
When I tried to connect to the database I receive errors as such (Python 3.5, Neo4j 3.5.1). The errors are identical regardless of whether I attempt to pass the bolt or http addresses directly. They are still the default addresses. I am able to connect using the officially supported neo4j bolt driver (1.7.1), but not py2neo (4.1.3) which I would prefer to use as an interface.

```
`from py2neo import Graph
g = Graph(password = 'password')
````
```Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/py2neo/database.py", line 88, in __new__
    inst = cls._instances[key]
KeyError: '1dd14af494824058e61abe2bb95cadc4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/py2neo/database.py", line 305, in __new__
    database = Database(uri, **settings)
  File "/usr/local/lib/python3.5/dist-packages/py2neo/database.py", line 92, in __new__
    from py2neo.internal.http import HTTPDriver, HTTPSDriver
  File "/usr/local/lib/python3.5/dist-packages/py2neo/internal/http.py", line 26, in <module>
    from neo4j.addressing import SocketAddress
  File "/usr/local/lib/python3.5/dist-packages/neo4j/addressing.py", line 26, in <module>
    from neo4j.exceptions import AddressError
ImportError: cannot import name 'AddressError'
```

Likewise
```
from py2neo import Database
db = Database()
```
yields
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/py2neo/database.py", line 88, in __new__
    inst = cls._instances[key]
KeyError: '6a27b93fae4fd6ece8144af722dc8768'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/py2neo/database.py", line 92, in __new__
    from py2neo.internal.http import HTTPDriver, HTTPSDriver
  File "/usr/local/lib/python3.5/dist-packages/py2neo/internal/http.py", line 26, in <module>
    from neo4j.addressing import SocketAddress
  File "/usr/local/lib/python3.5/dist-packages/neo4j/addressing.py", line 26, in <module>
    from neo4j.exceptions import AddressError
ImportError: cannot import name 'AddressError'
```
With the hash as key differing.

**Comment by technige** [comment]
Py2neo 4.1 depends on the official 1.6 driver but is incompatible with the 1.7 driver. Therefore, if you have  both py2neo 4.1 and the 1.7 driver installed in the same environment, you have a conflict.

To use py2neo, downgrade to the 1.6 driver.

**Comment by GeoWonk** [comment]
Thanks!
