### ISSUE TITLE
BoltConnector doesn't respect `secure=True` setting

### ISSUE THREAD

**Issue by twall** [technige/py2neo#745]
In `BoltConnector.open`, `encrypted` should be set in the kwargs to `connect` if `cx_data` has `secure=True` in it:

```
    def open(self, cx_data):

        def connector(address_, **kwargs):
            return connect(address_, auth=cx_data["auth"], **kwargs)

        address = (cx_data["host"], cx_data["port"])
        self.pool = ConnectionPool(connector, address)
```

The result is that connections are always dropped if TLS is required.

```
>>> tx = graph.begin()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/py2neo/database.py", line 346, in begin
    return Transaction(self, autocommit)
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/py2neo/database.py", line 758, in __init__
    self.transaction = self.connector.begin()
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/py2neo/internal/connectors.py", line 290, in begin
    tx = self.pool.acquire()
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/neobolt/direct.py", line 694, in acquire
    return self.acquire_direct(self.address)
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/neobolt/direct.py", line 587, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/py2neo/internal/connectors.py", line 225, in connector
    return connect(address_, auth=cx_data["auth"], **kwargs)
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/neobolt/direct.py", line 945, in connect
    raise last_error
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/neobolt/direct.py", line 937, in connect
    connection = _handshake(s, resolved_address, der_encoded_server_certificate, **config)
  File "/Users/twall/.conda/envs/plex-search/lib/python3.6/site-packages/neobolt/direct.py", line 883, in _handshake
    raise ServiceUnavailable("Connection to %r closed without handshake response" % (resolved_address,))
neobolt.exceptions.ServiceUnavailable: Connection to ('127.0.0.1', 7687) closed without handshake response
```

**Comment by thomas-schulze-entwicklerschmiede** [comment]
@twall 
Did You happen to find a suitable solution here?

Best regards

**Comment by twall** [comment]
I ended up patching the code, something like this:
```
    def patch_encryption(cls):
        # Work around bug in py2neo
        from neobolt import security
        if not getattr(security.SecurityPlan.build, 'patched', None):
            old_build = security.SecurityPlan.build
            def build_encrypted(**config):
                config['encrypted'] = 1
                return old_build(**config)
            security.SecurityPlan.build = build_encrypted
            security.SecurityPlan.build.patched = True
```

**Comment by thomas-schulze-entwicklerschmiede** [comment]
@twall I must admit that I am not that deep in the code - where did You put that?

**Comment by twall** [comment]
You can run it from anywhere, just do it before you attempt a connection.

**Comment by thomas-schulze-entwicklerschmiede** [comment]
Hm, I get
`
Failed to establish secure connection to 'EOF occurred in violation of protocol (_ssl.c:1056)'
`

**Comment by twall** [comment]
You'll get that if the patch isn't installed.  You have to run the patch code before anything else.
