### ISSUE TITLE
reason[Errno 111]

### ISSUE THREAD

**Issue by Zoher15** [technige/py2neo#748]
**Hey there,** 

**Just started using py2neo. Was running a simple command:**

```
from py2neo import Graph
graph = Graph(password="xxxx")
print(graph.run("MATCH (n) WHERE EXISTS(n.sssp) RETURN n").to_table())
```
Python Version 3.7.1. 
Miniconda3 Environment. Py2neo was the first package installed.
Do note that I am able to connect to localhost:7474 using firefox.

**Error:**
```Traceback (most recent call last):
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/neobolt/direct.py", line 809, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "neo4script.py", line 5, in <module>
    print(graph.run("MATCH (n) WHERE EXISTS(n.sssp) RETURN n").to_table())
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/py2neo/database.py", line 526, in run
    return self.begin(autocommit=True).run(cypher, parameters, **kwparameters)
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/py2neo/database.py", line 805, in run
    entities=entities))
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/py2neo/internal/connectors.py", line 285, in run
    return self._run_1(statement, parameters, graph, keys, entities)
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/py2neo/internal/connectors.py", line 234, in _run_1
    cx = self.pool.acquire()
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/neobolt/direct.py", line 698, in acquire
    return self.acquire_direct(self.address)
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/neobolt/direct.py", line 591, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/py2neo/internal/connectors.py", line 225, in connector
    return connect(address_, auth=cx_data["auth"], **kwargs)
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/neobolt/direct.py", line 949, in connect
    raise last_error
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/neobolt/direct.py", line 939, in connect
    s = _connect(resolved_address, **config)
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/neobolt/direct.py", line 821, in _connect
    raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error))
neobolt.exceptions.ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason [Errno 111] Connection refused)
```

**OS if it helps:**

```(base) [zkachwal@h2 FactCheckGraph-Neo4j]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
```
@technige any ideas?

**Comment by technige** [comment]
Unfortunately, I'm not able to diagnose local network issues. The product uses regular TCP connections and, if no alternative port is specified, it will try to connect to port 7687, as here. You will first need to ascertain whether you have a server problem (is the server running and listening on port 7687? is it being blocked by a firewall? etc) or a client problem (am I connecting to the right host and port?).
