### ISSUE TITLE
Py2neo v4 outputs do not match documentation, error: Cypher literal values of type py2neo.data.Walkable are not supported?

### ISSUE THREAD

**Issue by RyanHuangNLP** [technige/py2neo#759]
follow the document 
```
a = Node("Person", name="Alice")
b = Node("Person", name="Bob")
c = Node("Person", name="Mike")
ab = Relationship(a, "KNOWS", b)
ac = Relationship(a, "KNOWS", c)
w = ab + Relationship(b, "LIKES", c) + ac
print(w)
```

but raise error

```
Traceback (most recent call last):
  File "/Users/ramseyhuang/PycharmProjects/neo4j/test.py", line 16, in <module>
    print(w)
  File "/Users/ramseyhuang/anaconda3/envs/neo4j/lib/python3.7/site-packages/py2neo/data.py", line 673, in __repr__
    return xstr(cypher_repr(self))
  File "/Users/ramseyhuang/anaconda3/envs/neo4j/lib/python3.7/site-packages/py2neo/cypher/__init__.py", line 71, in cypher_repr
    return encoder.encode_value(value)
  File "/Users/ramseyhuang/anaconda3/envs/neo4j/lib/python3.7/site-packages/py2neo/cypher/encoding.py", line 196, in encode_value
    (type(value).__module__, type(value).__name__))
TypeError: Cypher literal values of type py2neo.data.Walkable are not supported
```

**Comment by tsitsu1** [comment]
hi
i'm using jupyter notebook and anaconda env'
and get same issu
Cypher literal values of type py2neo.data.Walkable are not supported
