### ISSUE TITLE
python multiprocessing can result in "neobolt.exceptions.ServiceUnavailable: Failed to read from defunct connection"

### ISSUE THREAD

**Issue by motey** [technige/py2neo#790]
I am not sure if this a py2neo or neobolt issue...
I am trying to insert some stuff from some subprocess workers (`multiprocessing.Process`-module), which works fine.
But as soon as iam trying to access the DB from the parent process before starting my workers, some of them will have issues connecting to the neo4j DB.
It feels like there is something going wrong in the connection pool management (?)
Here is a boiled down example to recreate the error:
```python
import multiprocessing
from py2neo import Graph, Node
import time

neo4j_url = "bolt://localhost:7687"


class Worker(multiprocessing.Process):
    node_count = 20

    def run(self):
        print("'{}' starts".format(self.name))
        g = Graph(neo4j_url)
        for i in range(0, self.node_count):
            tx = g.begin()
            tx.run("CREATE (n:Thing) SET n.name = {}".format(i))
        print("'{}' commits".format(self.name))
        tx.commit()
        print("'{}' done".format(self.name))


g = Graph(neo4j_url)
# If this line is disabled, the error wont happen
thing_count = g.run("MATCH (n:Thing) RETURN count(n) as cnt").data()[0]["cnt"]
print(thing_count)

worker_1 = Worker()
worker_1.name = "Worker 1"
worker_2 = Worker()
worker_2.name = "Worker 2"

worker_1.start()
worker_2.start()

worker_2.join()
worker_1.join()
``` 
This result in the error for worker_1. Worker_2 runs without exception.
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/myuser/Repos/git/dzdgitlab/python-sketches-and-tests/perfomance-tests/py2neo/multiprocess-insert.py", line 16, in run
    tx.run("CREATE (n:Thing) SET n.name = {}".format(i))
  File "/home/myuser/.local/lib/python3.7/site-packages/py2neo/database.py", line 859, in run
    entities=entities))
  File "/home/myuser/.local/lib/python3.7/site-packages/py2neo/internal/connectors.py", line 297, in run
    return self._run_in_tx(statement, parameters, tx, graph, keys, entities)
  File "/home/myuser/.local/lib/python3.7/site-packages/py2neo/internal/connectors.py", line 285, in _run_in_tx
    result.keys()   # force receipt of RUN summary, to detect any errors
  File "/home/myuser/.local/lib/python3.7/site-packages/py2neo/internal/hydration/__init__.py", line 77, in keys
    self._on_more()
  File "/home/myuser/.local/lib/python3.7/site-packages/py2neo/internal/connectors.py", line 265, in fetch
    tx.fetch()
  File "/home/myuser/.local/lib/python3.7/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/home/myuser/.local/lib/python3.7/site-packages/neobolt/direct.py", line 464, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/myuser/.local/lib/python3.7/site-packages/neobolt/direct.py", line 752, in on_failure
    self.connection.reset()
  File "/home/myuser/.local/lib/python3.7/site-packages/neobolt/direct.py", line 384, in reset
    self.sync()
  File "/home/myuser/.local/lib/python3.7/site-packages/neobolt/direct.py", line 531, in sync
    detail_delta, summary_delta = self.fetch()
  File "/home/myuser/.local/lib/python3.7/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/home/myuser/.local/lib/python3.7/site-packages/neobolt/direct.py", line 443, in _fetch
    self._receive()
  File "/home/myuser/.local/lib/python3.7/site-packages/neobolt/direct.py", line 491, in _receive
    raise self.Error(message)
neobolt.exceptions.ServiceUnavailable: Failed to read from defunct connection ('localhost', 7687) (Address(host='127.0.0.1', port=7687))
``` 
Before deep diving in the py2neo/neobolt driver and possibly losing my mind, i wanted to ask if somebody had a similar issue? Is this some expected behavior? If yes, what i am doing wrong?

**Comment by motey** [comment]
Ok, writing down this boiled down version has helped a little bit.
I can fix this by replacing
```python
g = Graph(neo4j_url)
# If this line is disabled, the error wont happen
thing_count = g.run("MATCH (n:Thing) RETURN count(n) as cnt").data()[0]["cnt"]
print(thing_count)
```
with 
```python
tx = Graph(neo4j_url).begin()
thing_count = tx.run("MATCH (n:Thing) RETURN count(n) as cnt").data()[0]["cnt"]
print(thing_count)
```
Now we run this query in a seperated transaction which helps to bypass the connection lost for the worker. 
But i still dont understand whats happening here. 
Why does this isolated adhoc transaction influence the connection of a later started subprocess?

**Comment by technige** [comment]
Py2neo is not designed to work with multiprocessing. The problem will be related to the caching of `Graph` objects, and the consequence of these objects then being shared across multiple processes.

I may address compatibility with multiprocessing at some point in the future, but I have no immediate plans to do so.

**Comment by Jricci1** [comment]
I am getting the same error 

```neobolt.exceptions.ServiceUnavailable: Failed to read from defunct connection ('hobby-dmldiegnhcgngbkenphdchel.dbs.graphenedb.com', 24787) (Address(host='34.229.164.223', port=24787))```

I have my application running on Heroku and I am getting that error only after a while without using my application, and I only receive that error the first time, then it gets fixed.

It seems to me that the connection to the database gets closed or something.

**Comment by motey** [comment]
@Jricci1 
Sounds more like the loadbalancer issue (because Heroku) have a look here https://github.com/neo4j/neo4j-python-driver/issues/205#issuecomment-349239859 
There are some more issues to this topic

**Comment by motey** [comment]
FTR: with py2neo `2020.0.0` creating new transactions per process like in https://github.com/technige/py2neo/issues/790#issuecomment-582975743
does not work for me reliable anymore 
It looks like py2neo is mixing queries and results now.. i have to investigate for details

**Comment by motey** [comment]
Update:
tested with `py2neo-2020.0.dev0` and `py2neo-2020.0.0`

```python
import multiprocessing
from py2neo import Graph


class Worker(multiprocessing.Process):
    node_count = 100

    def run(self):
        print("'{}' starts".format(self.name))
        g_worker = Graph()
        for i in range(0, self.node_count):
            tx_worker = g_worker.begin()
            tx_worker.run("CREATE (n:Thing) SET n.name = {}".format(i))
        print("'{}' commits".format(self.name))
        tx_worker.commit()
        print("'{}' done".format(self.name))


tx = Graph().begin()
thing_count = tx.run("MATCH (n:Thing) RETURN count(n) as cnt").data()[0]["cnt"]
print(thing_count)

worker_1 = Worker()
worker_1.name = "Worker 1"
worker_2 = Worker()
worker_2.name = "Worker 2"
worker_3 = Worker()
worker_3.name = "Worker 3"

worker_1.start()
worker_2.start()
worker_3.start()

worker_2.join()
worker_3.join()
worker_1.join()
``` 
results in 

``` 
'Worker 1' starts
'Worker 2' starts
'Worker 3' starts
Process Worker 1:
Process Worker 3:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/py2neo/client/__init__.py", line 462, in acquire
    cx = self._free_list.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/user/Repos/git.connect.dzd-ev.de/pubmedsucker/tmp.py", line 12, in run
    tx_worker = g_worker.begin()
  File "/home/user/.local/lib/python3.8/site-packages/py2neo/database/__init__.py", line 432, in begin
    return Transaction(self, autocommit,
  File "/home/user/.local/lib/python3.8/site-packages/py2neo/database/work.py", line 69, in __init__
    self._transaction = self._connector.begin(self._graph.name,
  File "/home/user/.local/lib/python3.8/site-packages/py2neo/client/__init__.py", line 873, in begin
    cx = self.acquire(graph_name, readonly=readonly)
  File "/home/user/.local/lib/python3.8/site-packages/py2neo/client/__init__.py", line 766, in acquire
    return pool.acquire(timeout=self.acquire_timeout, force_reset=force_reset)
  File "/home/user/.local/lib/python3.8/site-packages/py2neo/client/__init__.py", line 481, in acquire
    raise RuntimeError("Unable to acquire connection")
RuntimeError: Unable to acquire connection
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/py2neo/client/__init__.py", line 462, in acquire
    cx = self._free_list.popleft()
IndexError: pop from an empty deque
```
