### ISSUE TITLE
Can't use NEO4J_AUTH env for authentication

### ISSUE THREAD

**Issue by Pistacchione** [technige/py2neo#795]
Hi,

I see in the library it's possible to use `NEO4J_AUTH` env for user and password autentication.

But the partition separator used into `connectors.py` file is `:` instead of `/` as described in neo4j documentation [here](https://neo4j.com/docs/operations-manual/current/docker/introduction/#docker-auth) so the library authentication fail.

Thanks

**Comment by technige** [comment]
There was never any intention for these to be aligned, and the py2neo usage pre-dates the settings for the official Docker image anyway. This won't be changed in py2neo.

**Comment by Pistacchione** [comment]
Hi @technige 

Sorry I didn't know that `NEO4J_AUTH` env was not related to the official settings.

Anyway maybe I think aligned the env could be something useful for everyone who uses neo4j docker images.

Thanks

**Comment by meseta** [comment]
Hey @technige I just encountered this myself and spent several hours. I understand the issue with NEO4J_AUTH, however there's seems to be a deeper issue where even when explicit `auth` is provided, the environmental variable NEO4J_AUTH is still used if it exists, which I think is potentially unwanted behaviour.

**Steps to repro:**
Python 3.9.1 on Ubuntu 20 (WSL1 on Windows 10)
py2neo 2021.0.1
neo4j 4.2 docker

1. set environmental variable NEO4J_AUTH="" (can be any value that is not a valid login, including empty string)
2. connect to server using `auth` tuple 
```py
from py2neo import Graph
g = Graph("bolt://localhost", auth=("noe4j", "test")
```

**Expected result:**
py2neo uses `auth=("neo4j", "test")` to make the connection

**Actual result:**
```
py2neo.database.work.ClientError: [Security.Unauthorized] The client is unauthorized due to authentication failure.
```
Removing NEO4J_AUTH from the environment completely resolves the issue, however this is not always possible.

It seems to me that the intent of the code in `ConnectionProfile` ([here](https://github.com/technige/py2neo/blob/45af6c306aa338192c4a9738ec2deddc6e3c0dce/py2neo/client/config.py#L227) is supposed to use the `auth` value where provided, falling back to the NEO4J_AUTH env var, however the test above seems to imply that it doe snot, and that the existence of the NEO4J_AUTH variable in the environment prevents any use of the `auth` value

In my use-case, I have NEO4J_AUTH set in the environment due to testing with the docker image, and as @Pistacchione mentioned previously, the separator format is different. I can work around this issue by explicitly unsetting the environmental variable.

Here's some debug outputs in case they're helpful:
When NEO4J_AUTH is unset (username/password for server is neo4j and test)
```
>>> from py2neo import Graph
>>> g = Graph("bolt://localhost", auth=("neo4j", "test"))
{'auth': ('neo4j', 'test')}
{'secure': False, 'verify': True, 'scheme': 'bolt', 'user': 'neo4j', 'password': 'test', 'address': IPv4Address(('localhost', 7687)), 'auth': ('neo4j', 'test'), 'host': 'localhost', 'port': 7687, 'port_number': 7687, 'protocol': 'bolt', 'uri': 'bolt://neo4j@localhost:7687'}
{}
Adding connection pool for profile ConnectionProfile('bolt://neo4j@localhost:7687')
Trying to acquire connection from pool <ConnectionPool profile=ConnectionProfile('bolt://neo4j@localhost:7687') in_use=0 free=0 spare=100>
[#0000] C: (Dialing <localhost:7687>)
[#F746] S: (Accepted)
[#F746] C: <BOLT>
[#F746] C: <PROTOCOL> 4.1 | 4.0 | 3.0 | 2.0
[#F746] S: <PROTOCOL> 4.1
[#F746] C: HELLO {'user_agent': 'py2neo/2021.0.1 Python/3.9.1-final-0 (linux)', 'scheme': 'basic', 'principal': 'neo4j', 'credentials': '*******'}
[#F746] C: (Sent 110 bytes)
[#F746] S: SUCCESS {'server': 'Neo4j/4.2.3', 'connection_id': 'bolt-1411'}
Acquired connection <py2neo.client.bolt.Bolt4x1 object at 0x7f27c30349a0>
Releasing connection <py2neo.client.bolt.Bolt4x1 object at 0x7f27c30349a0>
>>> exit()
```

When NEO4J_AUTH is set to blank (`NEO4J_AUTH=` in env file)
```
>>> from py2neo import Graph
>>> g = Graph("bolt://localhost", auth=("neo4j", "test"))
{'auth': ('neo4j', 'test')}
{'secure': False, 'verify': True, 'scheme': 'bolt', 'user': 'neo4j', 'password': 'test', 'address': IPv4Address(('localhost', 7687)), 'auth': ('neo4j', 'test'), 'host': 'localhost', 'port': 7687, 'port_number': 7687, 'protocol': 'bolt', 'uri': 'bolt://neo4j@localhost:7687'}
{}
Adding connection pool for profile ConnectionProfile('bolt://neo4j@localhost:7687')
Trying to acquire connection from pool <ConnectionPool profile=ConnectionProfile('bolt://neo4j@localhost:7687') in_use=0 free=0 spare=100>
[#0000] C: (Dialing <localhost:7687>)
[#F74D] S: (Accepted)
[#F74D] C: <BOLT>
[#F74D] C: <PROTOCOL> 4.1 | 4.0 | 3.0 | 2.0
[#F74D] S: <PROTOCOL> 4.1
[#F74D] C: HELLO {'user_agent': 'py2neo/2021.0.1 Python/3.9.1-final-0 (linux)', 'scheme': 'basic', 'principal': 'neo4j', 'credentials': '*******'}
[#F74D] C: (Sent 114 bytes)
[#F74D] S: FAILURE {'code': 'Neo.ClientError.Security.Unauthorized', 'message': 'The client is unauthorized due to authentication failure.'}
Traceback (most recent call last):
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/__init__.py", line 742, in acquire
    cx = self._free_list.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/database/__init__.py", line 358, in __init__
    self.service = GraphService(profile, **settings)
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/database/__init__.py", line 189, in __init__
    self._connector = Connector(profile, **connector_settings)
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/__init__.py", line 893, in __init__
    self.add_pools(self._profile)
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/__init__.py", line 913, in add_pools
    pool = ConnectionPool.open(
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/__init__.py", line 570, in open
    seeds = [pool.acquire() for _ in range(init_size or cls.default_init_size)]
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/__init__.py", line 570, in <listcomp>
    seeds = [pool.acquire() for _ in range(init_size or cls.default_init_size)]
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/__init__.py", line 749, in acquire
    cx = self.connect()
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/__init__.py", line 706, in connect
    cx = Connection.open(self.profile, user_agent=self.user_agent,
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/__init__.py", line 141, in open
    return Bolt.open(profile, user_agent=user_agent,
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/bolt.py", line 220, in open
    bolt._hello()
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/bolt.py", line 668, in _hello
    self._audit(response)
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/bolt.py", line 641, in _audit
    task.audit()
  File "/home/yuan/.local/share/virtualenvs/knowledge-Fltsug3-/lib/python3.9/site-packages/py2neo/client/bolt.py", line 1089, in audit
    raise self._failure
py2neo.database.work.ClientError: [Security.Unauthorized] The client is unauthorized due to authentication failure.
>>> exit()
```
