### ISSUE TITLE
AttributeError when creating uniqueness constraint 

### ISSUE THREAD

**Issue by zhxh1** [technige/py2neo#803]
I tried to use the code below to create uniqueness constraints. 

```python
import py2neo

graph = py2neo.Graph(uri, password=password)
print("Connected.")
graph.schema.create_uniqueness_constraint("node_type", "primary_key")
print("Done")
```

It was fine yesterday, but it does not work now:
```bash
Connected.
Traceback (most recent call last):
  File "debug.py", line 7, in <module>
    graph.schema.create_uniqueness_constraint("node_type", "primary_key")
  File "/home/user/envs/conda/envs/py37/lib/python3.7/site-packages/py2neo/database.py", line 658, in create_uniqueness_constraint
    self.graph.run(cypher).close()
AttributeError: 'GraphService' object has no attribute 'run'
```

I am using `py2neo==5.0b1`, `Python==3.7.7` and `neo4j==4.0.3`.

**Comment by kingoodie** [comment]
I've got the same problem right now.
