### ISSUE TITLE
ValueError: Connection does not belong to this pool in commit

### ISSUE THREAD

**Issue by adralak** [technige/py2neo#829]
Hello, I am having an issue when committing a transaction in the database.

This error only happens when I am trying to add a large amount of data to the database at once. 
The exact traceback is:
Traceback (most recent call last):
  File "file.py", line 373, in main
    tx.commit()
  File "/home/user/.local/lib/python3.6/site-packages/py2neo/database.py", line 929, in commit
    return self._connector.commit(self._transaction)
  File "/home/user/.local/lib/python3.6/site-packages/py2neo/client/__init__.py", line 980, in commit
    return cx.commit(tx)
  File "/home/user/.local/lib/python3.6/site-packages/py2neo/client/bolt.py", line 266, in commit
    self._write_request(0x2F))
  File "/home/user/.local/lib/python3.6/site-packages/py2neo/client/bolt.py", line 409, in _sync
    self._wait(response)
  File "/home/user/.local/lib/python3.6/site-packages/py2neo/client/bolt.py", line 404, in _wait
    self.release()
  File "/home/user/.local/lib/python3.6/site-packages/py2neo/client/__init__.py", line 212, in release
    self._on_release(self)
  File "/home/user/.local/lib/python3.6/site-packages/py2neo/client/__init__.py", line 524, in <lambda>
    on_release=lambda c: self.release(c))
  File "/home/user/.local/lib/python3.6/site-packages/py2neo/client/__init__.py", line 573, in release
    raise ValueError("Connection %r does not belong to this pool" % cx)
ValueError: Connection <py2neo.client.bolt.Bolt2 object at 0x7f68fad712e8> does not belong to this pool

It may be possible to fix this issue by committing smaller chunks of data at once, but it would be nice to understand why committing larger amounts of data does not work and have it be mentioned in the documentation.

I thank you in advance for the help.

**Comment by adn201** [comment]
This happen to me often I am almost in production and I am realizing that py2neo is not what it seems to be, I am getting this exception together with wire network issues, this is frustrating. wondering if you will fix soon

**Comment by adn201** [comment]
This issue is present on the latest library 2020, is there some workaround ?
or something I am missing ? some configuration ? or should I close the connections somehow ?
