### ISSUE TITLE
AssertionError in match

### ISSUE THREAD

**Issue by HagridThick** [technige/py2neo#859]
i try to use graph_movie.run("MATCH (n:Movie) RETURN n LIMIT 25")
and graph_movie.service.kernel_version
and 
nodes = NodeMatcher(graph_movie)
p1 = nodes.match("Person", name="Keanu Reeves").first()

all of these get AssertionError,i tried run code in python3.7 and 3.8.

from py2neo import Graph
from py2neo.matching import *
g = Graph(
    "http://localhost:7474",
    username="hagrid",
    password="123456"
)
nodes = NodeMatcher(g)
keanu = nodes.match("Person", name="Keanu Reeves").first()
print(keanu)

 File "c:/Users/a/Documents/GitHub/law_neo4j/test.py", line 9, in <module>
    keanu = nodes.match("Person", name="Keanu Reeves").first()
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\matching.py", line 407, in first
    return self.graph.evaluate(*self._query_and_parameters())
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\database\__init__.py", line 498, in evaluate
    return self.auto().evaluate(cypher, parameters, **kwparameters)
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\database\work.py", line 164, in evaluate
    return self.run(cypher, parameters, **kwparameters).evaluate(0)
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\database\work.py", line 127, in run
    result = self._connector.auto_run(self.graph.name, cypher, parameters,
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\__init__.py", line 936, in auto_run
    result = cx.auto_run(graph_name, cypher, parameters, readonly=readonly)
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\http.py", line 170, in auto_run
    assert r.status == 200  # TODO: other codes
AssertionError

**Comment by technige** [comment]
So there are two issues here:
- The error message produced by py2neo is completely unhelpful, and needs to be fixed. Apologies for that.
- Why is the HTTP endpoint not returning a 200 status?

I can easily fix the first, but can't understand the second until I can see more information. Can you try running with a Bolt URL instead (temporarily) and see what happens? (e.g. `bolt://localhost:7687')

**Comment by HagridThick** [comment]
I forget the password for username"neo4j",“hagrid” is a user i add  by  neo4j Browser.
I can log in use "hagrid" and "123456" in http://localhost:7474。

graph_movie = Graph(
    "bolt://localhost:7687",
    #"http://localhost:7474",
    username="hagrid",
    password="123456"
)


Traceback (most recent call last):
  File "c:/Users/a/Documents/GitHub/law_neo4j/py2neo_graph_test.py", line 3, in <module>
    graph_movie = Graph(
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\database\__init__.py", line 358, in __init__
    self.service = GraphService(profile, **settings)
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\database\__init__.py", line 189, in __init__
    self._connector = Connector(profile, **connector_settings)
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\__init__.py", line 603, in __init__
    self.add_pools(self._profile)
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\__init__.py", line 623, in add_pools
    pool = ConnectionPool.open(
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\__init__.py", line 316, in open
    seeds = [pool.acquire() for _ in range(init_size or cls.default_init_size)]
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\__init__.py", line 316, in <listcomp>
    seeds = [pool.acquire() for _ in range(init_size or cls.default_init_size)]
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\__init__.py", line 457, in acquire
    cx = Connection.open(self.profile, user_agent=self.user_agent,
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\__init__.py", line 116, in open
    return Bolt.open(profile, user_agent=user_agent,
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\bolt.py", line 213, in open
    bolt._hello()
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\bolt.py", line 653, in _hello
    self._audit(response)
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\bolt.py", line 626, in _audit
    task.audit()
  File "D:\anaconda3\envs\python38-neo4j\lib\site-packages\py2neo\client\bolt.py", line 1062, in audit
    raise self._failure
py2neo.database.work.ClientError: [Security.Unauthorized] The client is unauthorized due to authentication failure.

**Comment by HagridThick** [comment]
hello,I try to create a new database to test,and use the username"neo4j" and password "123456"(i set while creating).
And it worked both bolt or http connections.
so i guess the problem is i didn't use the default user"neo4j".But i give "hagrid" the same authority Roles as "neo4j",maybe it's neo4j' bug.

**Comment by technige** [comment]
That makes sense. If the password was wrong, it's probably returning a 403 status, which py2neo isn't handling correctly. I can certainly fix that. Thanks for digging deeper.
