### ISSUE TITLE
Can't merge when setting __primarylabel__ and __primarykey__ on a per-node basis

### ISSUE THREAD

**Issue by panosprotopapas** [technige/py2neo#904]
Hello, by following the example in the documentation

```python
from py2neo import Graph, Node, Relationship

g = Graph(f'bolt://0.0.0.0:7688', auth=('neo4j', 'test'))

a = Node("Person", name="Alice", age=33)
b = Node("Person", name="Bob", age=44)
KNOWS = Relationship.type("KNOWS")
g.merge(KNOWS(a, b), "Person", "name")

c = Node("Company", name="ACME")
c.__primarylabel__ = "Company"
c.__primarykey__ = "name"
WORKS_FOR = Relationship.type("WORKS_FOR")
g.merge(WORKS_FOR(a, c) | WORKS_FOR(b, c))
```

I get a ValueError for the second merge operation:

```
Traceback (most recent call last):
  File ".../test.py", line 46, in <module>
    g.merge(WORKS_FOR(a, c) | WORKS_FOR(b, c))
  File ".../venv/lib/python3.9/site-packages/py2neo/database.py", line 667, in merge
    self.update(lambda tx: tx.merge(subgraph, label, *property_keys))
  File ".../venv/lib/python3.9/site-packages/py2neo/database.py", line 439, in update
    self._update(cypher, timeout=timeout)
  File ".../venv/lib/python3.9/site-packages/py2neo/database.py", line 464, in _update
    value = f(tx)
  File ".../venv/lib/python3.9/site-packages/py2neo/database.py", line 667, in <lambda>
    self.update(lambda tx: tx.merge(subgraph, label, *property_keys))
  File ".../venv/lib/python3.9/site-packages/py2neo/database.py", line 1120, in merge
    merge(self, primary_label, primary_key)
  File ".../venv/lib/python3.9/site-packages/py2neo/data/__init__.py", line 301, in __db_merge__
    raise ValueError("Primary label and primary key are required for MERGE operation")
ValueError: Primary label and primary key are required for MERGE operation
```

I'm using Python 3.9.5, and pip package and versions:

```
Package          Version
---------------- ---------
certifi          2020.12.5
cffi             1.14.5
chardet          4.0.0
cryptography     3.4.7
docker           5.0.0
elasticsearch    7.12.1
english          2020.7.0
idna             2.10
monotonic        1.6
neo4j            4.2.1
neotime          1.7.4
packaging        20.9
pansi            2020.7.3
pip              21.1.2
prompt-toolkit   3.0.18
py2neo           2021.1.2
pycparser        2.20
Pygments         2.9.0
pyparsing        2.4.7
pytz             2021.1
requests         2.25.1
setuptools       57.0.0
six              1.16.0
urllib3          1.26.4
wcwidth          0.2.5
websocket-client 1.0.1
```

**Comment by panosprotopapas** [comment]
Just saw the 2021.1.3 that fixes this :D
